"""initial_schema

Revision ID: 6e27f118ea48
Revises: 
Create Date: 2026-07-12 00:13:35.233236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e27f118ea48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('hometowns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('county', sa.String(length=32), nullable=True),
    sa.Column('hometown_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('landmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scene_type', sa.String(length=32), nullable=True),
    sa.Column('tier', sa.String(length=8), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('last_used_day', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_landmarks_user_name', 'landmarks', ['user_id', 'name'], unique=False)
    op.create_index('ix_landmarks_user_tier', 'landmarks', ['user_id', 'tier'], unique=False)
    op.create_index('ix_landmarks_user_used', 'landmarks', ['user_id', 'is_used'], unique=False)
    op.create_table('letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('place', sa.String(length=128), nullable=True),
    sa.Column('mood', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_letters_user_time', 'letters', ['user_id', 'timestamp'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('place_hint', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('analysis_status', sa.String(length=16), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_user_time', 'memories', ['user_id', 'timestamp'], unique=False)
    op.create_table('past_self_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('latent_place_affinities', sa.JSON(), nullable=True),
    sa.Column('sensory_biases', sa.JSON(), nullable=True),
    sa.Column('identity_signals', sa.JSON(), nullable=True),
    sa.Column('recent_memory_signals', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('postcards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('poem', sa.Text(), nullable=True),
    sa.Column('place', sa.String(length=128), nullable=True),
    sa.Column('landmark_id', sa.Integer(), nullable=True),
    sa.Column('landmark_description', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(length=32), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('search_image_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('letter_text', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmarks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_postcards_user_time', 'postcards', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_postcards_user_time', table_name='postcards')
    op.drop_table('postcards')
    op.drop_table('profiles')
    op.drop_table('past_self_profiles')
    op.drop_index('ix_memories_user_time', table_name='memories')
    op.drop_table('memories')
    op.drop_index('ix_letters_user_time', table_name='letters')
    op.drop_table('letters')
    op.drop_index('ix_landmarks_user_used', table_name='landmarks')
    op.drop_index('ix_landmarks_user_tier', table_name='landmarks')
    op.drop_index('ix_landmarks_user_name', table_name='landmarks')
    op.drop_table('landmarks')
    op.drop_table('hometowns')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
